### ISSUE TITLE
f'Block key not found

### ISSUE THREAD

**Issue by Jolpar** [jonajames/mc2mt#9]
Hi, 
Thanks for this powerful converter. However, I got an error [on this map](https://www.planetminecraft.com/project/ancient-athens/) :
```
Traceback (most recent call last):
  File "/home/----/Programmes/mc2mt/./mc2mt.py", line 59, in <module>
    converted = section_conversion.convert_section(
  File "/home/jpapir/Programmes/mc2mt/mc2mtlib/section_conversion.py", line 33, in convert_section
    for block in chunk.stream_blocks(0,section_y,True):
  File "/home/----/.local/lib/python3.10/site-packages/anvil/chunk.py", line 275, in stream_blocks
    yield block.convert()
  File "/home/----/.local/lib/python3.10/site-packages/anvil/block.py", line 133, in convert
    return Block.from_numeric_id(self.id, self.data)
  File "/home/----/.local/lib/python3.10/site-packages/anvil/block.py", line 103, in from_numeric_id
    raise KeyError(f'Block {key} not found')
KeyError: 'Block 6:13 not found'
```
Any idea of a the reason why I get this ? (it comes approximatly at the half of the processing, immediatly after the following lines :
```
Converting r.110.16.mca file 49 of 138
UnknownBlock~flowing_water~{'falling':'True', 'level':'5'}
```
Thanks for your work :)

**Comment by jonajames** [comment]
It seems to happen because anvil-parser does not know how to convert that block.

The numeric blocks conversion are defined here:
https://github.com/matcool/anvil-parser/blob/master/anvil/legacy_blocks.json

Indeeed there's no `6:13` and i'm not able to find it even on resources like https://minecraftitemids.com/
I suspect this is some custom block defined by some mod

You can try opening the map on a newer version of minecraft and maybe it will convert it to non-numeric ids.

Or you can find that json file and insert the mapping.

Can you tell me what that block should correspond to?

**Comment by Jolpar** [comment]
Thanks, indeed, it might be a custom blocks. Well : I'll try with a json file. I don't really know what sort of block this can be, but I met this error only one time, I guess it's not an essential feature. (I don't have minecraft myself, but I should get it to make conversion easier. However, I'm reluctant to support microsoft)

**Comment by Jolpar** [comment]
It worked ! Thanks. Adding a a random mapping to dirt to the json file worked. I have still some "unknown" blocks on the map, but it should be easier to fix. And also, the map is still at the level of the sky, so with clouds in the buildings. I will try to fix it.

**Comment by jonajames** [comment]
There's the option to change `cloud_height` within the world... Don't remembre how.
For unknown blocks you can define minecraft to minetest mappings.
See https://github.com/jonajames/mc2mt/tree/master/mc2mtlib/mods
If you do, please share them ;)
